# Generated by Django 4.1.7 on 2023-03-01 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bgColor", models.CharField(blank=True, max_length=100, null=True)),
                ("earSize", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "eyeBrowStyle",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("eyeStyle", models.CharField(blank=True, max_length=100, null=True)),
                ("faceColor", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "glassesStyle",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("hairColor", models.CharField(blank=True, max_length=100, null=True)),
                ("hairStyle", models.CharField(blank=True, max_length=100, null=True)),
                ("hatColor", models.CharField(blank=True, max_length=100, null=True)),
                ("hatStyle", models.CharField(blank=True, max_length=100, null=True)),
                ("mouthStyle", models.CharField(blank=True, max_length=100, null=True)),
                ("noseStyle", models.CharField(blank=True, max_length=100, null=True)),
                ("sex", models.CharField(blank=True, max_length=100, null=True)),
                ("shirtColor", models.CharField(blank=True, max_length=100, null=True)),
                ("shirtStyle", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avatar",
                        to="users.profile",
                    ),
                ),
            ],
        ),
    ]
