# Generated by Django 4.1.7 on 2023-03-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
