# Generated by Django 4.1.7 on 2023-02-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment_record",
            old_name="ticket",
            new_name="no_of_tickets",
        ),
        migrations.AddField(
            model_name="payment_record",
            name="tier",
            field=models.CharField(default="no", max_length=50),
        ),
    ]
