# Generated by Django 4.1.7 on 2023-03-01 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("match", "0001_initial"),
        ("wallet", "0003_paymentrecord_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="match",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="match.match"
            ),
        ),
    ]
