# Generated by Django 4.1.7 on 2023-03-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0004_paymentrecord_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
