# Generated by Django 4.1.7 on 2023-03-01 22:57

from django.db import migrations, models
import wallet.models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0006_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_hash",
            field=models.CharField(
                default=wallet.models.generate_hash_id, editable=False, max_length=36
            ),
        ),
    ]
