# Generated by Django 4.1.7 on 2023-02-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("home_team", models.CharField(max_length=100)),
                ("away_team", models.CharField(max_length=100)),
                ("home_team_logo", models.URLField()),
                ("away_team_logo", models.URLField()),
                ("venue", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Matches",
            },
        ),
    ]
